In [1]:
import pandas as pd
import numpy as np

In [2]:
#  import dataset
dataset = pd.read_csv('Absenteeism-data.csv')
dataset.head(10)

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   
5   3                  23  10/07/2015                     179   
6  10                  22  17/07/2015                     361   
7  20                  23  24/07/2015                     260   
8  14                  19  06/07/2015                     155   
9   1                  22  13/07/2015                     235   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   
5                51   38                  239.554               31          1   
6                52   28                  239.554               27          1   
7                50   36                  239.554               23          1   
8                12   34                  239.554               25          1   
9                11   37                  239.554               29          3   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2  
5         0     0                          2  
6         1     4                          8  
7         4     0                          4  
8         2     0                         40  
9         1     1                          8

In [3]:
# copying the data is a good practise
df = dataset.copy()
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
ID                           700 non-null int64
Reason for Absence           700 non-null int64
Date                         700 non-null object
Transportation Expense       700 non-null int64
Distance to Work             700 non-null int64
Age                          700 non-null int64
Daily Work Load Average      700 non-null float64
Body Mass Index              700 non-null int64
Education                    700 non-null int64
Children                     700 non-null int64
Pets                         700 non-null int64
Absenteeism Time in Hours    700 non-null int64
dtypes: float64(1), int64(10), object(1)
memory usage: 65.7+ KB


In [5]:
# romving a list of attributes from the dataframe
list_remove = ['ID']
df = df.drop(list_remove, axis=1)
df.head()

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [6]:
# the min and max values of the df
df['Reason for Absence'].min(),df['Reason for Absence'].max()

(0, 28)

In [7]:
df['Reason for Absence'].unique()

array([26,  0, 23,  7, 22, 19,  1, 11, 14, 21, 10, 13, 28, 18, 25, 24,  6,
       27, 17,  8, 12,  5,  9, 15,  4,  3,  2, 16], dtype=int64)

In [8]:
# length of the column
len(df['Reason for Absence'].unique())

28

In [9]:
df['Reason for Absence'] = df[['Reason for Absence']].astype(int)

In [10]:
# dummies for the variable reason for absence
reason_column = pd.get_dummies(df['Reason for Absence'],drop_first=True)
reason_column.head(10)
    

1   2   3   4   5   6   7   8   9   10 ...  18  19  21  22  23  24  25  26  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   1   
1   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
3   0   0   0   0   0   0   1   0   0   0 ...   0   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
5   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
6   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   1   0   0   0   0   
7   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   0   1   0   0   0   
8   0   0   0   0   0   0   0   0   0   0 ...   0   1   0   0   0   0   0   0   
9   0   0   0   0   0   0   0   0   0   0 ...   0   0   0   1   0   0   0   0   

   27  28  
0   0   0  
1   0   0  
2   0   0  
3   0   0  
4   0   0  
5   0   0  
6   0   0  
7   0   0  
8   0   0  
9   0   0  

[10 rows x 27 columns]

In [11]:
df.columns.values


array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [12]:
df = df.drop(['Reason for Absence'],axis=1)

In [13]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [14]:
#
Reason_type_1= reason_column.loc[:,1:14].max(axis=1)
Reason_type_2= reason_column.loc[:,15:17].max(axis=1)
Reason_type_3= reason_column.loc[:,18:22].max(axis=1)
Reason_type_4= reason_column.loc[:,22:].max(axis=1)


In [15]:
# concatinating df
df = pd.concat([Reason_type_1,Reason_type_2,Reason_type_3,Reason_type_4,df],axis=1)

In [16]:
df.head()

0  1  2  3        Date  Transportation Expense  Distance to Work  Age  \
0  0  0  0  1  07/07/2015                     289                36   33   
1  0  0  0  0  14/07/2015                     118                13   50   
2  0  0  0  1  15/07/2015                     179                51   38   
3  1  0  0  0  16/07/2015                     279                 5   39   
4  0  0  0  1  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

In [17]:
df.columns.values


array([0, 1, 2, 3, 'Date', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours'], dtype=object)

In [18]:
column_names = ['Reason_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4', 'Date', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [19]:
df.columns = column_names

In [20]:
df.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4        Date  \
0         0              0              0              1  07/07/2015   
1         0              0              0              0  14/07/2015   
2         0              0              0              1  15/07/2015   
3         1              0              0              0  16/07/2015   
4         0              0              0              1  23/07/2015   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [21]:
# check point
df_reason_mod = df.copy()
df_reason_mod.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4        Date  \
0         0              0              0              1  07/07/2015   
1         0              0              0              0  14/07/2015   
2         0              0              0              1  15/07/2015   
3         1              0              0              0  16/07/2015   
4         0              0              0              1  23/07/2015   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          1         2     1                          4  
1               31          1         1     0                          0  
2               31          1         0     0                          2  
3               24          1         2     0                          4  
4               30          1         2     1                          2

In [22]:
# data column
type(df_reason_mod['Date'][0])

str

In [23]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'],format='%d/%m/%Y')

In [24]:
# usig the forloop
list_month = []

for i in range(df_reason_mod.shape[0]):
    list_month.append(df_reason_mod['Date'][i].month)
    

In [25]:
len(list_month)

700

In [26]:
df_reason_mod['Month_value'] = list_month

In [27]:
df_reason_mod.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4       Date  \
0         0              0              0              1 2015-07-07   
1         0              0              0              0 2015-07-14   
2         0              0              0              1 2015-07-15   
3         1              0              0              0 2015-07-16   
4         0              0              0              1 2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          1         2     1                          4   
1               31          1         1     0                          0   
2               31          1         0     0                          2   
3               24          1         2     0                          4   
4               30          1         2     1                          2   

   Month_value  
0            7  
1            7  
2            7  
3            7  
4            7

In [28]:
# week day using a function, forloop can also so the job, but forloop is slow
def date_to_weekday(date_value):
    return date_value.weekday()

In [29]:
df_reason_mod['day of the week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [30]:
df_reason_mod.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4       Date  \
0         0              0              0              1 2015-07-07   
1         0              0              0              0 2015-07-14   
2         0              0              0              1 2015-07-15   
3         1              0              0              0 2015-07-16   
4         0              0              0              1 2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          1         2     1                          4   
1               31          1         1     0                          0   
2               31          1         0     0                          2   
3               24          1         2     0                          4   
4               30          1         2     1                          2   

   Month_value  day of the week  
0            7                1  
1            7                1  
2            7                2  
3            7                3  
4            7                3

In [31]:
# education column, 1->under graduate, 2->graduate, 3->postgraduate, 4-> masters or phd
df_reason_mod['Education'].unique()

array([1, 3, 2, 4], dtype=int64)

In [32]:
# counting the values
df_reason_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

In [33]:
# combining the minority eduction level together
df_reason_mod['Education'] = df_reason_mod['Education'].map({1:0,2:1,3:1,4:1})

In [34]:
df_reason_mod['Education'].unique()

array([0, 1], dtype=int64)

In [35]:
df_reason_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [36]:
# check point
df_preproccessed = df_reason_mod.copy()
df_preproccessed.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4       Date  \
0         0              0              0              1 2015-07-07   
1         0              0              0              0 2015-07-14   
2         0              0              0              1 2015-07-15   
3         1              0              0              0 2015-07-16   
4         0              0              0              1 2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Month_value  day of the week  
0            7                1  
1            7                1  
2            7                2  
3            7                3  
4            7                3

In [37]:
# target variable

target = np.where(df_preproccessed['Absenteeism Time in Hours'] > df_preproccessed['Absenteeism Time in Hours'].median(),1,0)

In [38]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [39]:
df_preproccessed['Excessive Absentism'] = target

In [40]:
df_preproccessed.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4       Date  \
0         0              0              0              1 2015-07-07   
1         0              0              0              0 2015-07-14   
2         0              0              0              1 2015-07-15   
3         1              0              0              0 2015-07-16   
4         0              0              0              1 2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Month_value  day of the week  Excessive Absentism  
0            7                1                    1  
1            7                1                    0  
2            7                2                    0  
3            7                3                    1  
4            7                3                    0

In [41]:
#
target.sum() / target.shape[0]

0.45571428571428574

In [42]:
# droping
data_with_target = df_preproccessed.drop(['Absenteeism Time in Hours'],axis=1)

In [43]:
(data_with_target is df_preproccessed)

False

In [44]:
data_with_target.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4       Date  \
0         0              0              0              1 2015-07-07   
1         0              0              0              0 2015-07-14   
2         0              0              0              1 2015-07-15   
3         1              0              0              0 2015-07-16   
4         0              0              0              1 2015-07-23   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Month_value  day of the week  \
0               30          0         2     1            7                1   
1               31          0         1     0            7                1   
2               31          0         0     0            7                2   
3               24          0         2     0            7                3   
4               30          0         2     1            7                3   

   Excessive Absentism  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0

In [45]:
data_with_target = data_with_target.drop(['Date'],axis=1)

In [46]:
data_with_target.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4  \
0         0              0              0              1   
1         0              0              0              0   
2         0              0              0              1   
3         1              0              0              0   
4         0              0              0              1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Month_value  day of the week  \
0               30          0         2     1            7                1   
1               31          0         1     0            7                1   
2               31          0         0     0            7                2   
3               24          0         2     0            7                3   
4               30          0         2     1            7                3   

   Excessive Absentism  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0

In [47]:
data_with_target.columns.values

array(['Reason_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month_value', 'day of the week',
       'Excessive Absentism'], dtype=object)

In [48]:
data_with_target= data_with_target[['Reason_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4','Month_value', 'day of the week',
                    'Transportation Expense', 'Distance to Work', 'Age','Daily Work Load Average',
                    'Body Mass Index', 'Education','Children', 'Pets','Excessive Absentism']]

In [49]:
data_with_target.head()

Reason_1  Reason_type_2  Reason_type_3  Reason_type_4  Month_value  \
0         0              0              0              1            7   
1         0              0              0              0            7   
2         0              0              0              1            7   
3         1              0              0              0            7   
4         0              0              0              1            7   

   day of the week  Transportation Expense  Distance to Work  Age  \
0                1                     289                36   33   
1                1                     118                13   50   
2                2                     179                51   38   
3                3                     279                 5   39   
4                3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Excessive Absentism  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0

In [50]:
data_with_target.shape

(700, 15)

In [51]:
# splitting the predictors and the target variable
#X ->predictors, y-> target

X =  data_with_target.iloc[:,:-1]
y = data_with_target.iloc[:,-1]
print(X.shape,y.shape)

(700, 14) (700,)


In [52]:
# spliting the training and the test data
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(560, 14) (560,)
(140, 14) (140,)


In [53]:
# standridizing the input data as required by ANN
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

C:\Users\abanfo\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\abanfo\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\abanfo\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype uint8, int64, float64 were all converted to float64 by StandardScaler.
  """


In [54]:
import keras

Using TensorFlow backend.


In [55]:
from keras.models import Sequential
from keras.layers import Dense

In [56]:
# intialize ANN
classifier = Sequential()
# input layer and the first layer
classifier.add(Dense(output_dim = 8,input_dim= 14, activation='relu',kernel_initializer = 'uniform'))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\abanfo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=14, activation="relu", kernel_initializer="uniform", units=8)`
  after removing the cwd from sys.path.


In [57]:
#  second layer
classifier.add(Dense(output_dim = 8, activation='relu',kernel_initializer = 'uniform'))
#  third layer
classifier.add(Dense(output_dim = 8, activation='relu',kernel_initializer = 'uniform'))
#  output layer
classifier.add(Dense(output_dim = 1, activation='sigmoid',kernel_initializer = 'uniform'))


C:\Users\abanfo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=8)`
  
C:\Users\abanfo\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=8)`
  after removing the cwd from sys.path.
C:\Users\abanfo\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", kernel_initializer="uniform", units=1)`
  


In [58]:
# compiling ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [60]:
# train the model
classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
560/560 [==============================] - 1s 1ms/step - loss: 0.6930 - acc: 0.5304
Epoch 2/100
560/560 [==============================] - 0s 171us/step - loss: 0.6926 - acc: 0.5339
Epoch 3/100
560/560 [==============================] - 0s 174us/step - loss: 0.6923 - acc: 0.5339
Epoch 4/100
560/560 [==============================] - 0s 184us/step - loss: 0.6921 - acc: 0.5339
Epoch 5/100
560/560 [==============================] - 0s 207us/step - loss: 0.6919 - acc: 0.5339
Epoch 6/100
560/560 [==============================] - 0s 168us/step - loss: 0.6917 - acc: 0.5339
Epoch 7/100
560/560 [==============================] - 0s 192us/step - loss: 0.6916 - acc: 0.5339
Epoch 8/100
560/560 [==============================] - 0s 184us/step - loss: 0.6915 - acc: 0.5339
Epoch 9/100
560/560 [==============================] - 0s 174us/step - loss: 0.6914 - acc: 0.5339
Epoch 10/100
560/560 [==============================] - 0s 173us/step - loss: 0.6913 - acc: 0.5339
Epoch 11/100
560/560 

560/560 [==============================] - 0s 140us/step - loss: 0.6910 - acc: 0.5339
Epoch 84/100
560/560 [==============================] - 0s 138us/step - loss: 0.6909 - acc: 0.5339
Epoch 85/100
560/560 [==============================] - 0s 131us/step - loss: 0.6909 - acc: 0.5339
Epoch 86/100
560/560 [==============================] - 0s 166us/step - loss: 0.6909 - acc: 0.5339
Epoch 87/100
560/560 [==============================] - 0s 140us/step - loss: 0.6909 - acc: 0.5339
Epoch 88/100
560/560 [==============================] - 0s 166us/step - loss: 0.6909 - acc: 0.5339
Epoch 89/100
560/560 [==============================] - 0s 141us/step - loss: 0.6909 - acc: 0.5339
Epoch 90/100
560/560 [==============================] - 0s 156us/step - loss: 0.6909 - acc: 0.5339
Epoch 91/100
560/560 [==============================] - 0s 138us/step - loss: 0.6909 - acc: 0.5339
Epoch 92/100
560/560 [==============================] - 0s 160us/step - loss: 0.6910 - acc: 0.5339
Epoch 93/100
560/560 [=

In [61]:
# predictiong
y_pred = classifier.predict(X_test)
y_pred

array([[0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.4663688 ],
       [0.466

In [62]:
y_pred = (y_pred >0.5)
y_pred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [70]:
# confision matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm = pd.DataFrame(cm)
cm

0  1
0  82  0
1  58  0

In [ ]:
# wrong model, couldnt identify the 